export const SET_SESSION = 'SET_SESSION'
export const GET_USER = 'GET_USER'
export const SET_USER = 'SET_USER'

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR'
